// src/utils/emojiData.js
// Curated emoji library, ~620 entries across 9 categories, hand-picked so
// every section is actually useful (not padded with skin-tone variants).
// Each entry: { c: character, n: lowercase name for search }.
// Adding more later is easy — just append; search and indexing are lazy.

const cat = (id, name, icon, emojis) => ({ id, name, icon, emojis });
const e = (c, n) => ({ c, n });

export const EMOJI_CATEGORIES = [
  cat('smileys', 'Smileys', '😀', [
    e('😀','grinning'), e('😃','smiley'), e('😄','smile'), e('😁','grin'),
    e('😆','laughing'), e('😅','sweat smile'), e('🤣','rofl'), e('😂','joy'),
    e('🙂','slightly smiling'), e('🙃','upside down'), e('🫠','melting'),
    e('😉','wink'), e('😊','blush'), e('😇','innocent halo'),
    e('🥰','smiling hearts'), e('😍','heart eyes'), e('🤩','star eyes'),
    e('😘','kiss'), e('😗','kissing'), e('😚','kissing closed eyes'),
    e('😙','kissing smile'), e('🥲','smile tear'), e('😋','yum'),
    e('😛','tongue'), e('😜','wink tongue'), e('🤪','zany'),
    e('😝','squint tongue'), e('🤑','money mouth'), e('🤗','hugging'),
    e('🤭','hand over mouth'), e('🫢','open eyes hand mouth'),
    e('🫣','peeking'), e('🤫','shushing'), e('🤔','thinking'),
    e('🫡','saluting'), e('🤐','zipper mouth'), e('🤨','raised eyebrow'),
    e('😐','neutral'), e('😑','expressionless'), e('😶','no mouth'),
    e('🫥','dotted line face'), e('😏','smirk'), e('😒','unamused'),
    e('🙄','eye roll'), e('😬','grimace'), e('🤥','lying'),
    e('😌','relieved'), e('😔','pensive'), e('😪','sleepy'),
    e('🤤','drooling'), e('😴','sleeping'), e('😷','mask'),
    e('🤒','thermometer'), e('🤕','head bandage'), e('🤢','nausea'),
    e('🤮','vomit'), e('🤧','sneezing'), e('🥵','hot'),
    e('🥶','cold'), e('🥴','woozy'), e('😵','dizzy'),
    e('🤯','exploding head'), e('🤠','cowboy'), e('🥳','party'),
    e('🥸','disguise'), e('😎','sunglasses'), e('🤓','nerd'),
    e('🧐','monocle'), e('😕','confused'), e('🫤','diagonal mouth'),
    e('😟','worried'), e('🙁','slight frown'), e('☹️','frown'),
    e('😮','open mouth'), e('😯','hushed'), e('😲','astonished'),
    e('😳','flushed'), e('🥺','pleading'), e('🥹','holding back tears'),
    e('😦','frowning open'), e('😧','anguished'), e('😨','fearful'),
    e('😰','anxious sweat'), e('😥','disappointed relief'), e('😢','cry'),
    e('😭','sob'), e('😱','scream'), e('😖','confounded'),
    e('😣','persevere'), e('😞','disappointed'), e('😓','sweat'),
    e('😩','weary'), e('😫','tired'), e('🥱','yawn'),
    e('😤','steam'), e('😡','pout'), e('😠','angry'),
    e('🤬','swearing'), e('😈','smiling devil'), e('👿','angry devil'),
    e('💀','skull'), e('☠️','skull crossbones'), e('💩','poop'),
    e('🤡','clown'), e('👹','ogre'), e('👺','goblin'),
    e('👻','ghost'), e('👽','alien'), e('👾','alien monster'),
    e('🤖','robot'),
  ]),

  cat('people', 'People', '👋', [
    e('👋','wave'), e('🤚','raised back'), e('🖐️','splayed hand'),
    e('✋','raised hand'), e('🖖','vulcan'), e('🫱','rightwards hand'),
    e('🫲','leftwards hand'), e('🫳','palm down'), e('🫴','palm up'),
    e('👌','ok'), e('🤌','pinched'), e('🤏','pinch'),
    e('✌️','victory'), e('🤞','crossed fingers'), e('🫰','finger heart'),
    e('🤟','love you'), e('🤘','rock on'), e('🤙','call me'),
    e('👈','left'), e('👉','right'), e('👆','up'), e('👇','down'),
    e('☝️','point up'), e('🫵','point you'), e('👍','thumbs up'),
    e('👎','thumbs down'), e('✊','fist'), e('👊','fist bump'),
    e('🤛','left fist'), e('🤜','right fist'), e('👏','clap'),
    e('🙌','raising hands'), e('🫶','heart hands'), e('👐','open hands'),
    e('🤲','palms up together'), e('🤝','handshake'), e('🙏','pray'),
    e('✍️','writing'), e('💅','nail polish'), e('🤳','selfie'),
    e('💪','muscle'), e('🦾','mech arm'), e('🦿','mech leg'),
    e('🦵','leg'), e('🦶','foot'), e('👂','ear'),
    e('🦻','hearing aid'), e('👃','nose'), e('🧠','brain'),
    e('🫀','heart organ'), e('🫁','lungs'), e('🦷','tooth'),
    e('🦴','bone'), e('👀','eyes'), e('👁️','eye'),
    e('👅','tongue'), e('👄','mouth'), e('🫦','biting lip'),
    e('👶','baby'), e('🧒','child'), e('👦','boy'),
    e('👧','girl'), e('🧑','adult'), e('👨','man'),
    e('👩','woman'), e('🧓','older'), e('👴','old man'),
    e('👵','old woman'), e('👮','officer'), e('🕵️','detective'),
    e('💂','guard'), e('🥷','ninja'), e('👷','construction worker'),
    e('🤴','prince'), e('👸','princess'), e('🧙','mage'),
    e('🧚','fairy'), e('🧛','vampire'), e('🧜','merperson'),
    e('🧝','elf'), e('🧞','genie'), e('🧟','zombie'),
    e('🦸','superhero'), e('🦹','supervillain'), e('🤰','pregnant'),
    e('🤱','breastfeeding'), e('👼','baby angel'), e('🎅','santa'),
    e('🤶','mrs claus'), e('🧑‍🎄','mx claus'),
  ]),

  cat('animals', 'Animals', '🐶', [
    e('🐶','dog'), e('🐱','cat'), e('🐭','mouse'), e('🐹','hamster'),
    e('🐰','rabbit'), e('🦊','fox'), e('🐻','bear'), e('🐼','panda'),
    e('🐻‍❄️','polar bear'), e('🐨','koala'), e('🐯','tiger'),
    e('🦁','lion'), e('🐮','cow'), e('🐷','pig'), e('🐽','pig nose'),
    e('🐸','frog'), e('🐵','monkey'), e('🙈','see no evil'),
    e('🙉','hear no evil'), e('🙊','speak no evil'), e('🐒','monkey full'),
    e('🐔','chicken'), e('🐧','penguin'), e('🐦','bird'),
    e('🐤','baby chick'), e('🐣','hatching chick'), e('🐥','front chick'),
    e('🦆','duck'), e('🦅','eagle'), e('🦉','owl'),
    e('🦇','bat'), e('🐺','wolf'), e('🐗','boar'),
    e('🐴','horse face'), e('🦄','unicorn'), e('🐝','bee'),
    e('🪱','worm'), e('🐛','bug'), e('🦋','butterfly'),
    e('🐌','snail'), e('🐞','ladybug'), e('🐜','ant'),
    e('🪰','fly'), e('🪲','beetle'), e('🦗','cricket'),
    e('🕷️','spider'), e('🦂','scorpion'), e('🐢','turtle'),
    e('🐍','snake'), e('🦎','lizard'), e('🦖','t-rex'),
    e('🦕','sauropod'), e('🐙','octopus'), e('🦑','squid'),
    e('🦐','shrimp'), e('🦞','lobster'), e('🦀','crab'),
    e('🐡','blowfish'), e('🐠','tropical fish'), e('🐟','fish'),
    e('🐬','dolphin'), e('🐳','spouting whale'), e('🐋','whale'),
    e('🦈','shark'), e('🐊','crocodile'), e('🐅','tiger full'),
    e('🐆','leopard'), e('🦓','zebra'), e('🦍','gorilla'),
    e('🦧','orangutan'), e('🐘','elephant'), e('🦣','mammoth'),
    e('🦛','hippo'), e('🦏','rhino'), e('🐪','camel'),
    e('🐫','two-hump camel'), e('🦒','giraffe'), e('🦘','kangaroo'),
    e('🐃','water buffalo'), e('🐂','ox'), e('🐄','cow full'),
    e('🐎','horse'), e('🐖','pig full'), e('🐏','ram'),
    e('🐑','ewe'), e('🦙','llama'), e('🐐','goat'),
    e('🦌','deer'), e('🐕','dog full'), e('🐩','poodle'),
    e('🦮','guide dog'), e('🐕‍🦺','service dog'), e('🐈','cat full'),
    e('🐈‍⬛','black cat'), e('🪶','feather'), e('🐓','rooster'),
    e('🦃','turkey'), e('🦤','dodo'), e('🦚','peacock'),
    e('🦜','parrot'), e('🦢','swan'), e('🦩','flamingo'),
    e('🕊️','dove'),
  ]),

  cat('nature', 'Nature', '🌸', [
    e('🌸','cherry blossom'), e('💮','white flower'), e('🪷','lotus'),
    e('🏵️','rosette'), e('🌹','rose'), e('🥀','wilted rose'),
    e('🌺','hibiscus'), e('🌻','sunflower'), e('🌼','blossom'),
    e('🌷','tulip'), e('🌱','seedling'), e('🪴','potted plant'),
    e('🌲','evergreen'), e('🌳','deciduous tree'), e('🌴','palm'),
    e('🌵','cactus'), e('🌾','rice'), e('🌿','herb'),
    e('☘️','shamrock'), e('🍀','four leaf clover'), e('🍁','maple leaf'),
    e('🍂','fallen leaves'), e('🍃','leaf wind'), e('🪨','rock'),
    e('🪵','wood'), e('☀️','sun'), e('🌝','full moon face'),
    e('🌞','sun face'), e('🌛','first quarter face'), e('🌜','last quarter face'),
    e('🌚','new moon face'), e('🌕','full moon'), e('🌖','waning gibbous'),
    e('🌗','last quarter'), e('🌘','waning crescent'), e('🌑','new moon'),
    e('🌒','waxing crescent'), e('🌓','first quarter'), e('🌔','waxing gibbous'),
    e('🌙','crescent moon'), e('🌎','globe americas'), e('🌍','globe europe'),
    e('🌏','globe asia'), e('🪐','ringed planet'), e('💫','dizzy'),
    e('⭐','star'), e('🌟','glow star'), e('✨','sparkles'),
    e('⚡','zap'), e('☄️','comet'), e('💥','collision'),
    e('🔥','fire'), e('🌪️','tornado'), e('🌈','rainbow'),
    e('☁️','cloud'), e('⛅','sun behind cloud'), e('⛈️','thunder cloud'),
    e('🌤️','sun small cloud'), e('🌥️','sun large cloud'), e('🌦️','sun rain'),
    e('🌧️','rain cloud'), e('🌨️','snow cloud'), e('🌩️','lightning cloud'),
    e('❄️','snowflake'), e('☃️','snowman'), e('⛄','snowman no snow'),
    e('💨','dash'), e('💧','droplet'), e('💦','sweat drops'),
    e('🌊','wave'),
  ]),

  cat('food', 'Food & Drink', '🍕', [
    e('🍏','green apple'), e('🍎','red apple'), e('🍐','pear'),
    e('🍊','orange'), e('🍋','lemon'), e('🍌','banana'),
    e('🍉','watermelon'), e('🍇','grapes'), e('🍓','strawberry'),
    e('🫐','blueberries'), e('🍈','melon'), e('🍒','cherries'),
    e('🍑','peach'), e('🥭','mango'), e('🍍','pineapple'),
    e('🥥','coconut'), e('🥝','kiwi'), e('🍅','tomato'),
    e('🍆','eggplant'), e('🥑','avocado'), e('🥦','broccoli'),
    e('🥬','leafy green'), e('🥒','cucumber'), e('🌶️','hot pepper'),
    e('🫑','bell pepper'), e('🌽','corn'), e('🥕','carrot'),
    e('🫒','olive'), e('🧄','garlic'), e('🧅','onion'),
    e('🥔','potato'), e('🍠','sweet potato'), e('🥐','croissant'),
    e('🥯','bagel'), e('🍞','bread'), e('🥖','baguette'),
    e('🫓','flatbread'), e('🥨','pretzel'), e('🥞','pancakes'),
    e('🧇','waffle'), e('🧀','cheese'), e('🍖','meat on bone'),
    e('🍗','poultry leg'), e('🥩','steak'), e('🥓','bacon'),
    e('🍔','burger'), e('🍟','fries'), e('🍕','pizza'),
    e('🌭','hotdog'), e('🥪','sandwich'), e('🌮','taco'),
    e('🌯','burrito'), e('🫔','tamale'), e('🥙','stuffed flatbread'),
    e('🧆','falafel'), e('🥚','egg'), e('🍳','cooking'),
    e('🥘','shallow pan'), e('🍲','pot of food'), e('🫕','fondue'),
    e('🥣','bowl spoon'), e('🥗','salad'), e('🍿','popcorn'),
    e('🧈','butter'), e('🧂','salt'), e('🥫','canned food'),
    e('🍱','bento'), e('🍘','rice cracker'), e('🍙','rice ball'),
    e('🍚','cooked rice'), e('🍛','curry'), e('🍜','noodles'),
    e('🍝','spaghetti'), e('🍠','roast sweet potato'),
    e('🍢','oden'), e('🍣','sushi'), e('🍤','tempura'),
    e('🍥','fish cake'), e('🥮','moon cake'), e('🍡','dango'),
    e('🥟','dumpling'), e('🥠','fortune cookie'), e('🥡','takeout'),
    e('🍦','soft serve'), e('🍧','shaved ice'), e('🍨','ice cream'),
    e('🍩','donut'), e('🍪','cookie'), e('🎂','birthday cake'),
    e('🍰','shortcake'), e('🧁','cupcake'), e('🥧','pie'),
    e('🍫','chocolate'), e('🍬','candy'), e('🍭','lollipop'),
    e('🍮','custard'), e('🍯','honey'), e('🍼','bottle'),
    e('🥛','milk'), e('☕','coffee'), e('🫖','teapot'),
    e('🍵','tea'), e('🍶','sake'), e('🍾','champagne'),
    e('🍷','wine'), e('🍸','cocktail'), e('🍹','tropical'),
    e('🍺','beer'), e('🍻','beers'), e('🥂','clink'),
    e('🥃','tumbler'), e('🥤','cup straw'), e('🧋','bubble tea'),
    e('🧃','juice box'), e('🧉','mate'), e('🧊','ice'),
  ]),

  cat('activities', 'Activities', '⚽', [
    e('⚽','soccer'), e('🏀','basketball'), e('🏈','football'),
    e('⚾','baseball'), e('🥎','softball'), e('🎾','tennis'),
    e('🏐','volleyball'), e('🏉','rugby'), e('🥏','frisbee'),
    e('🎱','8 ball'), e('🪀','yo-yo'), e('🏓','ping pong'),
    e('🏸','badminton'), e('🏒','ice hockey'), e('🏑','field hockey'),
    e('🥍','lacrosse'), e('🏏','cricket'), e('🪃','boomerang'),
    e('🥅','goal'), e('⛳','golf flag'), e('🪁','kite'),
    e('🏹','bow'), e('🎣','fishing'), e('🤿','diving mask'),
    e('🥊','boxing glove'), e('🥋','martial arts'), e('🎽','running shirt'),
    e('🛹','skateboard'), e('🛼','roller skate'), e('🛷','sled'),
    e('⛸️','ice skate'), e('🥌','curling stone'), e('🎿','ski'),
    e('⛷️','skier'), e('🏂','snowboarder'), e('🪂','parachute'),
    e('🏋️','weight lifter'), e('🤸','cartwheel'), e('🤼','wrestling'),
    e('🤽','water polo'), e('🤾','handball'), e('🧗','climbing'),
    e('🏇','jockey'), e('🧘','meditation'), e('🛀','bath'),
    e('🛌','sleeping bed'), e('🎪','circus'), e('🎭','performing arts'),
    e('🎨','artist palette'), e('🎬','clapper'), e('🎤','microphone'),
    e('🎧','headphones'), e('🎼','musical score'), e('🎹','piano'),
    e('🥁','drum'), e('🪘','long drum'), e('🎷','saxophone'),
    e('🎺','trumpet'), e('🎸','guitar'), e('🪕','banjo'),
    e('🎻','violin'), e('🪗','accordion'), e('🎲','die'),
    e('♟️','chess pawn'), e('🎯','dart'), e('🎳','bowling'),
    e('🎮','video game'), e('🕹️','joystick'), e('🎰','slot machine'),
    e('🧩','puzzle'),
  ]),

  cat('travel', 'Travel', '✈️', [
    e('🚗','car'), e('🚕','taxi'), e('🚙','suv'),
    e('🚌','bus'), e('🚎','trolleybus'), e('🏎️','race car'),
    e('🚓','police car'), e('🚑','ambulance'), e('🚒','fire engine'),
    e('🚐','minibus'), e('🛻','pickup'), e('🚚','truck'),
    e('🚛','articulated lorry'), e('🚜','tractor'), e('🛵','scooter'),
    e('🏍️','motorcycle'), e('🛺','auto rickshaw'), e('🚲','bicycle'),
    e('🛴','kick scooter'), e('🛹','skateboard'), e('🛼','roller skate'),
    e('🚏','bus stop'), e('🛣️','motorway'), e('🛤️','railway'),
    e('🛢️','oil drum'), e('⛽','fuel pump'), e('🚨','siren'),
    e('🚥','traffic light horizontal'), e('🚦','traffic light vertical'),
    e('🚧','construction'), e('⚓','anchor'), e('🪝','hook'),
    e('⛵','boat'), e('🛶','canoe'), e('🚤','speedboat'),
    e('🛳️','passenger ship'), e('⛴️','ferry'), e('🛥️','motor boat'),
    e('🚢','ship'), e('✈️','airplane'), e('🛩️','small airplane'),
    e('🛫','takeoff'), e('🛬','landing'), e('🪂','parachute'),
    e('💺','seat'), e('🚁','helicopter'), e('🚟','suspension railway'),
    e('🚠','mountain cableway'), e('🚡','aerial tramway'), e('🛰️','satellite'),
    e('🚀','rocket'), e('🛸','ufo'), e('🛎️','bellhop bell'),
    e('🧳','luggage'), e('⌛','hourglass'), e('⏳','hourglass flowing'),
    e('⌚','watch'), e('⏰','alarm clock'), e('⏱️','stopwatch'),
    e('🕰️','mantelpiece clock'), e('🌡️','thermometer'), e('🗺️','map'),
    e('🧭','compass'), e('🗽','statue of liberty'), e('🗼','tokyo tower'),
    e('🏰','castle'), e('🏯','japanese castle'), e('🏟️','stadium'),
    e('🎡','ferris wheel'), e('🎢','roller coaster'), e('🎠','carousel'),
    e('💈','barber'), e('🎪','circus tent'), e('🌁','bridge fog'),
    e('🌃','starry night'), e('🌄','sunrise mountain'), e('🌅','sunrise'),
    e('🌆','sunset city'), e('🌇','sunset'), e('🌉','golden gate'),
    e('🌌','milky way'), e('🎑','moon viewing'), e('🏞️','national park'),
    e('🏜️','desert'), e('🏖️','beach'), e('🏝️','desert island'),
    e('⛰️','mountain'), e('🏔️','snow mountain'), e('🌋','volcano'),
    e('🗻','mount fuji'), e('🏕️','camping'), e('🏠','house'),
    e('🏡','house garden'), e('🏘️','houses'), e('🏚️','derelict house'),
    e('🏗️','building construction'), e('🏢','office'), e('🏬','department store'),
    e('🏣','japanese post'), e('🏤','european post'), e('🏥','hospital'),
    e('🏦','bank'), e('🏨','hotel'), e('🏩','love hotel'),
    e('🏪','convenience store'), e('🏫','school'), e('🏛️','classical building'),
    e('⛪','church'), e('🕌','mosque'), e('🕍','synagogue'),
    e('🛕','hindu temple'), e('🕋','kaaba'), e('⛩️','shinto shrine'),
    e('🗿','moai'), e('🛖','hut'),
  ]),

  cat('objects', 'Objects', '💡', [
    e('💡','bulb'), e('🔦','flashlight'), e('🕯️','candle'),
    e('🪔','diya lamp'), e('🪞','mirror'), e('🪟','window'),
    e('🛏️','bed'), e('🛋️','couch'), e('🪑','chair'),
    e('🚪','door'), e('🚿','shower'), e('🛁','bathtub'),
    e('🧴','lotion'), e('🧷','safety pin'), e('🧹','broom'),
    e('🧺','basket'), e('🧻','toilet paper'), e('🪣','bucket'),
    e('🧼','soap'), e('🪥','toothbrush'), e('🪒','razor'),
    e('🧽','sponge'), e('🪠','plunger'), e('🚽','toilet'),
    e('💍','ring'), e('💎','gem'), e('👑','crown'),
    e('🎩','top hat'), e('🧢','cap'), e('🪖','helmet'),
    e('⛑️','rescue helmet'), e('👒','woman hat'), e('🎓','grad cap'),
    e('👓','glasses'), e('🕶️','sunglasses'), e('🥽','goggles'),
    e('🥼','lab coat'), e('🦺','safety vest'), e('👔','tie'),
    e('👕','t-shirt'), e('👚','blouse'), e('🧥','coat'),
    e('🧣','scarf'), e('🧤','gloves'), e('🧦','socks'),
    e('👖','jeans'), e('🩳','shorts'), e('👗','dress'),
    e('👘','kimono'), e('🥻','sari'), e('🩱','one-piece'),
    e('🩲','briefs'), e('👙','bikini'), e('👛','purse'),
    e('👜','handbag'), e('👝','clutch'), e('🛍️','shopping'),
    e('🎒','backpack'), e('👞','dress shoe'), e('👟','sneaker'),
    e('🥾','hiking boot'), e('🥿','flat shoe'), e('👠','heel'),
    e('👡','sandal'), e('🩴','flip-flop'), e('👢','boot'),
    e('📱','phone'), e('📲','phone arrow'), e('💻','laptop'),
    e('⌨️','keyboard'), e('🖥️','desktop'), e('🖨️','printer'),
    e('🖱️','mouse'), e('🖲️','trackball'), e('🕹️','joystick'),
    e('🗜️','clamp'), e('💽','minidisc'), e('💾','floppy'),
    e('💿','cd'), e('📀','dvd'), e('📼','vhs'),
    e('📷','camera'), e('📸','camera flash'), e('📹','video camera'),
    e('🎥','movie camera'), e('📽️','projector'), e('🎞️','film frames'),
    e('📞','phone receiver'), e('☎️','telephone'), e('📟','pager'),
    e('📠','fax'), e('📺','tv'), e('📻','radio'),
    e('🎙️','studio mic'), e('🎚️','level slider'), e('🎛️','knobs'),
    e('🧭','compass'), e('⏱️','stopwatch'), e('⏲️','timer'),
    e('⏰','alarm'), e('🕰️','mantelpiece clock'), e('⌚','watch'),
    e('📡','satellite antenna'), e('🔋','battery'), e('🪫','low battery'),
    e('🔌','plug'), e('💴','yen note'), e('💵','dollar note'),
    e('💶','euro note'), e('💷','pound note'), e('💰','money bag'),
    e('🪙','coin'), e('💳','credit card'), e('🧾','receipt'),
    e('💸','money flying'), e('💹','chart up yen'), e('💱','currency exchange'),
    e('💲','dollar sign'), e('🏧','atm'), e('✉️','envelope'),
    e('📧','email'), e('📨','incoming envelope'), e('📩','envelope arrow'),
    e('📤','outbox'), e('📥','inbox'), e('📦','package'),
    e('📫','closed mailbox flag'), e('📪','closed mailbox no flag'),
    e('📬','open mailbox flag'), e('📭','open mailbox no flag'),
    e('📮','postbox'), e('🗳️','ballot box'), e('✏️','pencil'),
    e('✒️','black nib'), e('🖋️','fountain pen'), e('🖊️','pen'),
    e('🖌️','paintbrush'), e('🖍️','crayon'), e('📝','memo'),
    e('💼','briefcase'), e('📁','folder'), e('📂','open folder'),
    e('🗂️','card index dividers'), e('📅','calendar'), e('📆','tear-off calendar'),
    e('🗒️','spiral notepad'), e('🗓️','spiral calendar'), e('📇','card index'),
    e('📈','chart up'), e('📉','chart down'), e('📊','bar chart'),
    e('📋','clipboard'), e('📌','pushpin'), e('📍','round pushpin'),
    e('📎','paperclip'), e('🖇️','linked paperclips'), e('📏','ruler'),
    e('📐','triangular ruler'), e('✂️','scissors'), e('🗃️','card file box'),
    e('🗄️','file cabinet'), e('🗑️','trash'), e('🔒','locked'),
    e('🔓','unlocked'), e('🔏','locked with pen'), e('🔐','locked with key'),
    e('🔑','key'), e('🗝️','old key'), e('🔨','hammer'),
    e('🪓','axe'), e('⛏️','pick'), e('⚒️','hammer and pick'),
    e('🛠️','hammer and wrench'), e('🗡️','dagger'), e('⚔️','crossed swords'),
    e('🔫','toy gun'), e('🪃','boomerang'), e('🏹','bow and arrow'),
    e('🛡️','shield'), e('🪚','saw'), e('🔧','wrench'),
    e('🪛','screwdriver'), e('🔩','nut and bolt'), e('⚙️','gear'),
    e('🗜️','clamp two'), e('⚖️','balance scale'), e('🦯','white cane'),
    e('🔗','link'), e('⛓️','chains'), e('🪝','hook two'),
    e('🧰','toolbox'), e('🧲','magnet'), e('🪜','ladder'),
    e('⚗️','alembic'), e('🧪','test tube'), e('🧫','petri dish'),
    e('🧬','dna'), e('🔬','microscope'), e('🔭','telescope'),
    e('📡','satellite dish'), e('💉','syringe'), e('🩸','blood drop'),
    e('💊','pill'), e('🩹','bandage'), e('🩺','stethoscope'),
    e('🚬','cigarette'), e('⚰️','coffin'), e('🪦','headstone'),
    e('⚱️','funeral urn'), e('🗿','statue'),
  ]),

  cat('symbols', 'Symbols', '✅', [
    e('❤️','red heart'), e('🧡','orange heart'), e('💛','yellow heart'),
    e('💚','green heart'), e('💙','blue heart'), e('💜','purple heart'),
    e('🖤','black heart'), e('🤍','white heart'), e('🤎','brown heart'),
    e('💔','broken heart'), e('❣️','heart exclamation'), e('💕','two hearts'),
    e('💞','revolving hearts'), e('💓','beating heart'), e('💗','growing heart'),
    e('💖','sparkling heart'), e('💘','heart arrow'), e('💝','heart ribbon'),
    e('💟','heart decoration'), e('🩷','pink heart'), e('🩵','light blue heart'),
    e('🩶','grey heart'), e('♥️','heart suit'), e('♣️','club suit'),
    e('♠️','spade suit'), e('♦️','diamond suit'), e('🃏','joker'),
    e('🀄','mahjong red dragon'), e('🎴','flower playing cards'),
    e('💯','100'), e('💢','anger'), e('💬','speech balloon'),
    e('👁️‍🗨️','eye in speech bubble'), e('🗨️','left speech bubble'),
    e('🗯️','right anger bubble'), e('💭','thought balloon'), e('💤','zzz'),
    e('♨️','hot springs'), e('💈','barber pole'), e('🛑','stop sign'),
    e('⚛️','atom'), e('🕉️','om'), e('✡️','star of david'),
    e('☸️','wheel of dharma'), e('☯️','yin yang'), e('✝️','cross'),
    e('☦️','orthodox cross'), e('☪️','star and crescent'), e('☮️','peace'),
    e('🕎','menorah'), e('🔯','six pointed star'), e('♈','aries'),
    e('♉','taurus'), e('♊','gemini'), e('♋','cancer'),
    e('♌','leo'), e('♍','virgo'), e('♎','libra'),
    e('♏','scorpio'), e('♐','sagittarius'), e('♑','capricorn'),
    e('♒','aquarius'), e('♓','pisces'), e('⛎','ophiuchus'),
    e('🆔','id'), e('🈳','vacancy'), e('🈹','discount'),
    e('Ⓜ️','m circle'), e('🆎','ab'), e('🅰️','a'),
    e('🅱️','b'), e('🆑','cl'), e('🅾️','o'),
    e('🆘','sos'), e('🚫','prohibited'), e('🔞','no one under 18'),
    e('📵','no phones'), e('🚭','no smoking'), e('❗','exclamation'),
    e('❓','question'), e('❕','white exclamation'), e('❔','white question'),
    e('‼️','double exclamation'), e('⁉️','exclamation question'), e('🔅','dim'),
    e('🔆','bright'), e('〽️','part alternation'), e('⚠️','warning'),
    e('🚸','children crossing'), e('🔱','trident'), e('⚜️','fleur-de-lis'),
    e('🔰','beginner'), e('♻️','recycle'), e('✅','check'),
    e('🈯','reserved'), e('💹','chart up'), e('❇️','sparkle'),
    e('✳️','eight spoked asterisk'), e('❎','cross mark button'), e('🌐','globe meridians'),
    e('💠','diamond dot'), e('Ⓜ️','circled m'), e('🌀','cyclone'),
    e('💤','sleep'), e('🏧','atm sign'), e('🚾','wc'),
    e('♿','wheelchair'), e('🅿️','parking'), e('🛗','elevator'),
    e('🈂️','service charge'), e('🛂','passport control'), e('🛃','customs'),
    e('🛄','baggage claim'), e('🛅','left luggage'), e('🚹','men'),
    e('🚺','women'), e('🚼','baby symbol'), e('🚻','restroom'),
    e('🚮','litter bin'), e('🎦','cinema'), e('📶','signal'),
    e('🈁','here'), e('🔣','symbols input'), e('ℹ️','info'),
    e('🔤','abc'), e('🔡','abcd lower'), e('🔠','abcd upper'),
    e('🆖','ng'), e('🆗','ok button'), e('🆙','up'),
    e('🆒','cool'), e('🆓','free'), e('0️⃣','keycap 0'),
    e('1️⃣','keycap 1'), e('2️⃣','keycap 2'), e('3️⃣','keycap 3'),
    e('4️⃣','keycap 4'), e('5️⃣','keycap 5'), e('6️⃣','keycap 6'),
    e('7️⃣','keycap 7'), e('8️⃣','keycap 8'), e('9️⃣','keycap 9'),
    e('🔟','keycap 10'), e('🔢','1234'), e('#️⃣','keycap hash'),
    e('*️⃣','keycap asterisk'), e('⏏️','eject'), e('▶️','play'),
    e('⏸️','pause'), e('⏯️','play pause'), e('⏹️','stop'),
    e('⏺️','record'), e('⏭️','next'), e('⏮️','prev'),
    e('⏩','fast forward'), e('⏪','rewind'), e('⏫','fast up'),
    e('⏬','fast down'), e('◀️','reverse'), e('🔼','up button'),
    e('🔽','down button'), e('➡️','right arrow'), e('⬅️','left arrow'),
    e('⬆️','up arrow'), e('⬇️','down arrow'), e('↗️','up right arrow'),
    e('↘️','down right arrow'), e('↙️','down left arrow'), e('↖️','up left arrow'),
    e('↕️','up down arrow'), e('↔️','left right arrow'), e('↩️','right hook'),
    e('↪️','left hook'), e('⤴️','arrow curve up'), e('⤵️','arrow curve down'),
    e('🔃','clockwise'), e('🔄','anticlockwise'), e('🔙','back'),
    e('🔚','end'), e('🔛','on'), e('🔜','soon'),
    e('🔝','top'), e('🔀','shuffle'), e('🔁','repeat'),
    e('🔂','repeat one'),
  ]),

  cat('flags', 'Flags', '🚩', [
    e('🏁','chequered'), e('🚩','triangular'), e('🎌','crossed flags'),
    e('🏴','black flag'), e('🏳️','white flag'), e('🏳️‍🌈','rainbow flag'),
    e('🏳️‍⚧️','trans flag'), e('🏴‍☠️','pirate flag'),
    e('🇺🇸','usa'), e('🇬🇧','uk'), e('🇨🇦','canada'),
    e('🇦🇺','australia'), e('🇮🇳','india'), e('🇯🇵','japan'),
    e('🇰🇷','south korea'), e('🇨🇳','china'), e('🇹🇼','taiwan'),
    e('🇭🇰','hong kong'), e('🇸🇬','singapore'), e('🇩🇪','germany'),
    e('🇫🇷','france'), e('🇪🇸','spain'), e('🇮🇹','italy'),
    e('🇵🇹','portugal'), e('🇳🇱','netherlands'), e('🇧🇪','belgium'),
    e('🇨🇭','switzerland'), e('🇦🇹','austria'), e('🇸🇪','sweden'),
    e('🇳🇴','norway'), e('🇫🇮','finland'), e('🇩🇰','denmark'),
    e('🇮🇪','ireland'), e('🇵🇱','poland'), e('🇨🇿','czechia'),
    e('🇬🇷','greece'), e('🇹🇷','turkey'), e('🇷🇺','russia'),
    e('🇺🇦','ukraine'), e('🇧🇷','brazil'), e('🇲🇽','mexico'),
    e('🇦🇷','argentina'), e('🇨🇱','chile'), e('🇨🇴','colombia'),
    e('🇵🇪','peru'), e('🇿🇦','south africa'), e('🇳🇬','nigeria'),
    e('🇰🇪','kenya'), e('🇪🇬','egypt'), e('🇮🇱','israel'),
    e('🇸🇦','saudi arabia'), e('🇦🇪','uae'), e('🇮🇷','iran'),
    e('🇮🇶','iraq'), e('🇵🇰','pakistan'), e('🇧🇩','bangladesh'),
    e('🇱🇰','sri lanka'), e('🇳🇵','nepal'), e('🇹🇭','thailand'),
    e('🇻🇳','vietnam'), e('🇵🇭','philippines'), e('🇮🇩','indonesia'),
    e('🇲🇾','malaysia'), e('🇳🇿','new zealand'),
  ]),
];

/**
 * Search across all categories for emojis whose name OR keyword starts with
 * (or contains) the query string. Returns at most `limit` results.
 * Empty/whitespace query returns [].
 */
export function searchEmojis(query, limit = 80) {
  const q = (query || '').trim().toLowerCase();
  if (!q) return [];
  const out = [];
  for (const cat of EMOJI_CATEGORIES) {
    for (const item of cat.emojis) {
      if (item.n.includes(q)) {
        out.push(item);
        if (out.length >= limit) return out;
      }
    }
  }
  return out;
}
